[build]
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/commande"
  to = "/.netlify/functions/commande"
  status = 200
  force = true

[[redirects]]
  from = "/api/commande-test"
  to = "/.netlify/functions/commande-test"
  status = 200
  force = true

[[redirects]]
  from = "/api/qr"
  to = "/.netlify/functions/qr"
  status = 200
  force = true

[[redirects]]
  from = "/api/webhooks/byteqs"
  to = "/.netlify/functions/webhook-byteqs"
  status = 200
  force = true

[[redirects]]
  from = "/api/merci"
  to = "/.netlify/functions/merci"
  status = 200
  force = true

[[redirects]]
  from = "/api/billets"
  to = "/.netlify/functions/billets"
  status = 200
  force = true

[[redirects]]
  from = "/r/7kQ9mN2pLx4vW8dR3hFs6bYt"
  to = "/r/7kQ9mN2pLx4vW8dR3hFs6bYt.html"
  status = 200
  force = true

[[redirects]]
  from = "/thank-you"
  to = "/thank-you.html"
  status = 200
  force = true
